### ISSUE TITLE
Add the ability for the link component to redirect with App Bridge

### ISSUE THREAD

**Issue by dan-gamble** [baoagency/polaris_view_components#116]
A use case I've recently had is wanting to redirect to a deep link with an app embed. I ended up creating a custom Stimulus controller and achieving it like so:

```erb
<%= polaris_button(url: theme_extension_deep_link(shop: @shop_origin), data: { controller: "app-bridge-redirect", action: "click->app-bridge-redirect#redirect" }) { "Enable" } %>
```

```javascript
import { Redirect } from '@shopify/app-bridge/actions'
import { Controller } from 'stimulus'

export default class extends Controller {
  initialize () {
    this.appBridgeRedirect = Redirect.create(window.app)
  }

  redirect (e) {
    e.preventDefault()

    this.appBridgeRedirect.dispatch(Redirect.Action.ADMIN_PATH, {
      path: this.url,
      newContext: true,
    })
  }

  get url () {
    return this.element.getAttribute('href')
  }
}
```

Would be good we could somehow find a decent API so the full [Redirect](https://shopify.dev/apps/tools/app-bridge/actions/navigation/redirect) API is exposed.

Initially I'm thinking:
```erb
<%= polaris_button(url: "/customers", redirect: "ADMIN_PATH") %>
```

**Comment by kirillplatonov** [comment]
Oh, yeah. I will need such button as well for the theme extension deep link 🙂

**Comment by kirillplatonov** [comment]
@dan-gamble I made this a second thought and I feel like tying this library with AppBridge won't be a good idea. The library provides UI and this controller is more about the app's business logic on how to handle redirects. What do you think?

**Comment by dan-gamble** [comment]
This was specifically about being able to allow an embedded app to use the [Redirect](https://shopify.dev/apps/tools/app-bridge/actions/navigation/redirect-navigate) feature of App Bridge. I think it does need to be intrinsically tied to App Bridge, personally.

With that said, I do see your point. The React Polaris library did extract all of their App Bridge specific bits out into a separate library so maybe that would make sense here too. Alternatively, we could add it to this library but not include it by default. It could be imported separately when needed. That way we still have a "one way of doing it".
