### ISSUE TITLE
Why is this component unknown?

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#169]
I dropped this example into index.html.erb and got this error. Are components like this in the demo browser not actually developed or is this due to something dumb I am doing? 

I can only assume it does work fine inside a frame in a non-embedded App, and since I am using an embedded app for my dev I cannot even use this code... just checking...

<pre><code>undefined method `polaris_navigation' for #&lt;ActionView::Base:0x00000000044110&gt;
Did you mean?  polaris_pagination
               polaris_caption</code></pre>
`<%= polaris_navigation do |navigation| %>
      <% navigation.item(
        url: "#",
        label: "Home",
        icon: "HomeMajor"
      ) %>
      <% navigation.item(
        url: "#",
        label: "Orders",
        icon: "OrdersMajor",
        badge: "15"
      ) %>
      <% navigation.item(
        url: "#",
        label: "Products",
        icon: "ProductsMajor"
      ) %>
    <% end %>`

**Comment by kirillplatonov** [comment]
Oh, that's my mistake. The navigation is a new component that has been just added and it will be included in the upcoming 0.7.0 release next week. But since it's already merged it has been deployed to the demo app (I need to fix that).

For now, you can use it from github:
```
gem 'polaris_view_components', github: 'baoagency/polaris_view_components', branch: 'main'
```
