### ISSUE TITLE
What is Shopify Navigation component from? 

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#174]
I get Links in Polaris. A universal think. I see Shopify Navigation component is using links, and a stack, and works well enough. But there does not seem to be an analog for that in Polaris Components from Shopify? The closest thing they offer is tabs, which is supposed to be used to group operations in the same context. 

I like the menu offering of this Shopify Navigation, but I am curious about how it evolved? For a perceived need? 

In the same vein, does anyone else think it is stupid that the Shopify Polaris Navigation component is for non=embedded Apps only and has to live in a frame? Is it because having a sidebar in our embedded Apps would confuse the merchant as it would be beside their sidebar and hence confusing?

**Comment by dan-gamble** [comment]
Are you referring to [this](https://polarisviewcomponents.org/lookbook/navigation/shopify_navigation/default)? If so, it's to replace the navigation you can set up in your embedded app.

It was just to offer the flexibility that comes with building your own full-stack app and not being bound to just what Shopify offers there.

In addition to that, I also believe there was an issue when you used the extension's navigation when it came to the host/shop domain being there for links. This caused issues with the JWT auth in the early days. Still might be there now but I haven't gone back to try this way yet after creating this component.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/7152041/146792999-8a2e6fe4-0906-4352-8b42-68d140dd5f01.png">

**Comment by resistorsoftware** [comment]
Um.. no. In fact, I did not even know that extension existed. Not sure how
that works. I am speaking of this specifically.

[image: Lookbook.png]
So a stack, holding some Navigation Items... Not sure where this comes from
exactly!

Dave

**Comment by forsbergplustwo** [comment]
@resistorsoftware Your image failed to post 😉

**Comment by forsbergplustwo** [comment]
https://polaris.shopify.com/components/navigation/navigation

**Comment by resistorsoftware** [comment]
@forsberg that is of no use as that is limited to non-embedded Apps, which defeats the purpose of using Shopify in my opinion. Whenever I see Apps external, I think, cop-out! But I know, you made millions off it, and no one cares what I think.

**Comment by resistorsoftware** [comment]
My image posting service is down, so I will speak of an URL: under Navigation, Shopify Navigation, default. That is what I speak of. Really, nothing more than 3 links, side by side, linking to pages. This is good! This is not part of Polaris anywhere I found, hence my questions!

**Comment by forsbergplustwo** [comment]
@resistorsoftware This? https://shopify.dev/apps/app-extensions/navigation-links

**Comment by resistorsoftware** [comment]
Well, since that is the second posting pointing that out, it must be it. I can't say I understand why we'd have a component to manually make those at our disposal then, but why not... I guess I will play with that aspect of Shopify to see what it does. Seems a bit intrusive? I can get the same look and feel from Tabs... but then they just display content in the same context, they are not meant to jump around. 

OK.. I will explore this further! See where it takes me. Thanks!

**Comment by resistorsoftware** [comment]
That was it. I set up my App to use that embedded navigation and it worked fine. Such confusion though! Guess I am still wondering why it exists in this project since it is "from" Shopify.

**Comment by dan-gamble** [comment]
I think it all ended up boiling down to auth, at the time. When JWT first started becoming a thing `home_path(shop=shop)` was needed for the auth to work. This is still the case, I think.

However, @kirillplatonov solved it in a better way in https://github.com/kirillplatonov/shopify-hotwire-sample using middleware, I believe. That, in theory, makes the component "redundant"

**Comment by resistorsoftware** [comment]
These links as per Shopify are indeed a strange thing. Why would they want us to setup navigation inside the App using Shopify, instead of inside our App using whatever approach we want? Regardless, it seems work, although it has a fair amount of obnoxious behaviors in how Shopify implemented it in embedded Sales Channels. I am so not impressed with Shopify at this point, they really were not prepared well to see so much team quit, drop the ball and then leave us in the cold with their half-baked expectations.
