### ISSUE TITLE
File type specific icons for Dropzone component

### ISSUE THREAD

**Issue by forsbergplustwo** [baoagency/polaris_view_components#182]
Just wanted to check if the additional complexity is worth it in your opinion, before submitting a PR for it :)

In Shopify admin -> Settings -> Files, shopify will show preview images for image file type, but also other specific icons for other files types. For example, PDFs use the `notes` icon and JSON files use the `code` icon from Polaris

![CleanShot 2022-01-06 at 15 27 24@2x](https://user-images.githubusercontent.com/1411883/148398775-53771e17-b455-4854-b68c-c434dd0405e6.png)

https://polaris-icons.shopify.com/

Most use cases of Dropzone will be for uploading images, but we have a use case where other file types will be uploaded also. So would look to add specific icons for the most common file types.

Thoughts?

**Comment by kirillplatonov** [comment]
I think that would be great! Some groups of types that come to mind: text/pdf, archives, code, video, audio. We could add a separate icon for each and keep the existing icon as a fallback.

**Comment by forsbergplustwo** [comment]
Awesome, will work on that and submit a PR 👍
