### ISSUE TITLE
How to Use This Library

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#203]
I throw a couple of buttons down. I want to use them. I doctored them up trying to figure this library out. 

    <%= polaris_button(id: "export", primary: true) { "Export A" } %>
    <%= polaris_button("data-controller": "export", primary: true) { "Export B" } %>

So I get two buttons. The first has a data-contrroller set to "polaris-button". What code runs for that controller? Is it the JS in the node_modules for the component button_controller.js? I gave it an ID just for kicks. Makes no diff to anything.

The first button is useless to me at this point. I cannot do anything with it, but it sure it pretty. 

The second button renders and I told it, hey, your data-controller is export, and I wrote a Stimulus controller called export_controller.js, and it connected to the button, and I could then listen to clicks. That seems ugly that I have to name my button controller? OK. Moving on, is the underlying code for buttons still a thing now that I renamed the controller? Am I somehow supposed to super() something to get the underlying code to run? By explicitly providing a data controller value, have I lost something, or is this correct all the way? 

What about the first button? Is that really the story? Use ERB to render some button and then what? Where is the meat? 

I can write a ton about how fabulous all this is, but it is hard trying to figure it out just by reading the code. Can anyone point out the obvious stuff I am missing here, and how I can do things better?

**Comment by saidMontufar** [comment]
Hey @resistorsoftware 👋 Curious to know if you managed to trigger any of the Stimulus controllers for buttons, popovers, etc.. I've tried about every single approach I have found on the internet but I continue to hit a wall every time. 

Any help with this Gem would be much appreciated 🙏

**Comment by resistorsoftware** [comment]
@saidMontufar 

Here is a button:
```
  <div data-controller="shop">
    <%= polaris_button("data-action": "click->shop#inventory") { "Generate Report" } %>
```

I have a stimulus controller **shop_controller**, so I can write some JS,  a function labelled **inventory()** that works fine.
Mostly it just works with that simple pattern. I go very far with nothing much more than that for starters. I have since became capable of doing a lot more, but that is not for here and now.
