### ISSUE TITLE
Date Picker. Anyone worked on that Polaris Component? 

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#206]
I would love to help out here, as I need to collect a start date and end date for reports. 

If anyone has a branch already started with that code, I would love to help polish it into use. If not, and I hear crickets chirping, I will have to consider my options! I am not fully up to speed on birthing new components although I get it, there are plenty lying around here in this repo I can use as a basis.

**Comment by kirillplatonov** [comment]
Hey. As far as I know, no one is working on that component.

Feel free to add it. This will be a very useful addition to the library.

**Comment by kirillplatonov** [comment]
It seems like browsers support for the native HTML date/time pickers is pretty good now: https://caniuse.com/input-datetime
So you can just use polaris text field with date type:
```rb
<%= form.polaris_text_field(:some_date, type: :date) %>
```

Under the hood it will use Rails methods `#date_field_tag` to generate native HTML date input.

**Comment by resistorsoftware** [comment]
I used a flexible and complete flatpickr project. Was super easy to integrate and had a heck of a lot more going for it than the Shopify Polaris one.

**Comment by kirillplatonov** [comment]
Yeah, that's another great alternative.
