### ISSUE TITLE
Button url is not a thing? 

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#209]
I am curious. Threw down this. 

     <%= polaris_button(url: "/fizz/buzz", "data-action": "click->goose#gander") { "Shooter Jennings" } %>

Thinking the event passed to the controller would have a target.href to be used. But no. Nothing of the sort. Polaris buttons have an url for this, but the view components throw an error as nothing takes and url prop and produces an href.

**Comment by dan-gamble** [comment]
Are you sure `e.target` is the actual button/anchor? Polaris puts quite a few elements in the anchor and one of those could be the `e.target`.

Should work if you do:
```javascript
const anchor = e.target.closest('a')
anchor.getAttribute('href')
```

**Comment by resistorsoftware** [comment]
Thanks! Yes.
