### ISSUE TITLE
Resource Picker

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#213]
Shopify made a simple and somewhat useful resource picker with Polaris back in the day. It never really offered up much customization, but it did provide some practicality to the project when they first tried to sell us on it. 

Now that we are well into the era of quick and dirty popups etc, and the bugs in resource lists and items are seemingly a thing of the past, with filters richer in features than ever, are there any examples of people using this ViewComponent version of Polaris to deliver resource pickers? 

I am curious. Has anyone done that yet and published it?

**Comment by kirillplatonov** [comment]
It's definitely possible to build one with this library. We have all ingredients in place: modals, text fields, and resource lists. 

But as far as I know, no one shared their implementation yet. Feel free to contribute. Having at least the UI for Resource Picker in this library would be great!
