### ISSUE TITLE
https://polarisviewcomponents.org/ is down

### ISSUE THREAD

**Issue by stevemar** [baoagency/polaris_view_components#230]
Hi there 👋 

Navigating over to https://polarisviewcomponents.org/ results in a `ERR_TOO_MANY_REDIRECTS` error and the site fails to load. I tried using an incognito browser too, same result.

**Comment by kirillplatonov** [comment]
Hey @stevemar 
Thanks for noticing that. Fixed now 🙂

**Comment by stevemar** [comment]
Awesome! Thanks @kirillplatonov ! And thank you for the wonderful tool you maintain
