### ISSUE TITLE
Functionality of array input (multiple)

### ISSUE THREAD

**Issue by Kurbm** [baoagency/polaris_view_components#234]
Hey,

is there a way, to use the polaris formbuilder with multiple: true?

So I would like to allow the user duplicating an input field, which gets saved in an array.

On normal rails form_with function, I can add multiple: true to the input field, but it looks like this does not work with the polaris formbuilder

**Comment by kirillplatonov** [comment]
Yes, try passing it via `input_options`:
```rb
form.polaris_text_field :input_name, input_options: { multiple: true }
```

**Comment by Kurbm** [comment]
@kirillplatonov amazing. Works like a charm. Thank you very much
