### ISSUE TITLE
How to actually filter a list with the component filter - with_resource_list

### ISSUE THREAD

**Issue by Kurbm** [baoagency/polaris_view_components#236]
Hey,

I'm just trying to create a resource list of all products, which actually can be filtered with the resource list component.

I've tried to connect this list with a stimulus controller, but this did not work out and the list did not get filtered.

Does anyone has an idea, how to actually achieve a filtering function with this component?

Thanks in advance.

**Comment by kirillplatonov** [comment]
Hey @Kurbm,

You can implement filtering with Hotwire Turbo: https://www.colby.so/posts/filtering-tables-with-rails-and-hotwire
Also, [Ransack](https://activerecord-hackery.github.io/ransack/) gem could be useful for applying filters on the backend.
