### ISSUE TITLE
How to use autocomplete component?

### ISSUE THREAD

**Issue by vfonic** [baoagency/polaris_view_components#242]
Hi!

Thank you for the awesome gem!
I'm trying to use this instead of React Polaris and I'm a little bit stuck.

I've rendered `polaris_autocomplete` component and I'm trying to simply assign a value to the text field when user selects an item (a vendor) from the autocomplete popover (from a list of vendors):

```erb
<%= polaris_autocomplete do |autocomplete| %>
  <% autocomplete.text_field(label: "Vendor", placeholder: "Start typing to search for artisan...") do |c| %>
    <% c.prefix do %>
      <%= polaris_icon(name: "IllustrationMajor") %>
    <% end %>
  <% end %>
  <% autocomplete.section do |section| %>
    <% @vendors.each do |vendor| %>
      <% section.option(label: vendor, value: vendor) %>
    <% end %>
  <% end %>
<% end %>
```

The default behavior doesn't populate the text field with the value selected. I also tried to override `Autocomplete` controller in JS and also tried to pass `polaris_autocomplete(data: { controller: 'vendors' })`, but that option gets ignored.

I'm not well versed with Stimulus and/or ViewComponents so it's a bit difficult for me to figure these things out. The lookbook documentation helps a lot! Thank you! I'm missing the JS part of the documentation. How to use gem's Stimulus controllers etc.

I also tried listening for `"polaris-autocomplete:change"`, but I don't know how?
Typing this in browser dev console (in app iframe container) doesn't get triggered:

```js
document.addEventListener('polaris-autocomplete:change', e => {
  console.log(e)
  debugger
})
```

I don't know what else to try except maybe `this.application.getControllerForElementAndIdentifier`, but that looks kinda ugly...

Is there any better way?

**Comment by vfonic** [comment]
Ok, I finally got it. :)

```js
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  static targets = ["autocomplete", "value"];

  connect() {
    const valueTarget = this.valueTarget;
    this.autocompleteTarget.addEventListener("polaris-autocomplete:change", ({ detail: { value } }) => {
      const textFieldController = this.application.getControllerForElementAndIdentifier(
        valueTarget,
        "polaris-text-field"
      );
      textFieldController.value = value;
    });
  }

  get autocompleteController() {
    return this.application.getControllerForElementAndIdentifier(this.autocompleteTarget, "polaris-autocomplete");
  }
}
```

```erb
<% form_layout.item(data: { controller: 'vendors' }) do %>
  <%= polaris_autocomplete(id: 'vendor_title_autocomplete', data: { 'vendors-target': 'autocomplete' }) do |autocomplete| %>
    <% autocomplete.text_field(
      name: :vendor_title,
      label: "Artisan",
      placeholder: "Start typing to search for artisan...",
      data: { 'vendors-target': 'value' }
    ) do |c| %>
      <% c.prefix do %>
        <%= polaris_icon(name: "IllustrationMajor") %>
      <% end %>
    <% end %>
    <% @vendors.each do |vendor| %>
      <% autocomplete.option(label: vendor, value: vendor) %>
    <% end %>
  <% end %>
<% end %>
```

Do you recommend a different approach?

Thanks!

**Comment by vfonic** [comment]
I refactored my Stimulus controller further so now it looks like this:

```js
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  static targets = ["autocomplete", "value"];

  connect() {
    this.autocompleteTarget.addEventListener("polaris-autocomplete:change", this.vendorSelected);
  }

  get popoverController() {
    return this.application.getControllerForElementAndIdentifier(
      this.element.querySelector('[data-polaris-autocomplete-target="popover"'),
      "polaris-popover"
    );
  }

  get textFieldController() {
    return this.application.getControllerForElementAndIdentifier(this.valueTarget, "polaris-text-field");
  }

  vendorSelected = ({ detail: { value } }) => {
    this.popoverController.forceHide();
    this.textFieldController.value = value;
  };
}
```

Shouldn't this be the default Autocomplete component functionality?

This is exactly how the original React Polaris Autocomplete component works:
https://polaris.shopify.com/components/forms/autocomplete

**Comment by kirillplatonov** [comment]
@vfonic great solution! You're right, this probably should be the default behavior of Autocomplete. At least for Basic autocomplete without multi-select. Feel free to open a PR for it 🙂
