### ISSUE TITLE
Focus on elements with keyboard

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#243]
I am curious. I have a text field input. If I use the tab key to exit the text field, the focus should naturally move to the next element in order, in my case a plain Polaris button. There is no indication though that the button has focus and is ready to be pressed. When a Polaris button gets focus, is it not supposed to have a CSS class that changes the state from no focus to focus? 

Seems like a simple usability issue. What am I missing here to ensure Polaris elements light up when focus is on them?

**Comment by kirillplatonov** [comment]
Fixed in #253. Will be included in v0.11.0.

**Comment by kirillplatonov** [comment]
And it's live. You can try here: https://polarisviewcomponents.org/lookbook/forms/form_layout/default
