### ISSUE TITLE
Resource List and rendering stats

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#248]
I pretty much copy and pasted the working example code into my App. When I render it, I get no stats. Nada. All the resource items render fine, but not the total count. What could that be? 

    <%= polaris_resource_list(
      resource_name: {
        singular: "event",
        plural: "events",
      },
      items: @events,
      total_items_count: @events.count
    ) do %>

In this case, @events is a valid array of objects representing the items, and the count is also reasonable. But nothing at all renders as in **Showing 2 of 50 events**

**Comment by resistorsoftware** [comment]
So strange. The example renders, but the generated HTML looks nothing like the component I am seeing at version 0.10.1. 
There is no HeaderWrapper or any of the element denoting a header. So how does the demo site work, when I cannot find a stitch of code that takes the total_items_count and the boolean of show_header and renders said header? 

    <div class="Polaris-Card">
      <div class="Polaris-ResourceList__ResourceListWrapper">
         <ul resource_name="singular event plural events" show_header="true" items="{:id=>39, :url=>&quot;/events/39&quot;, :name=>&quot;Iggy Muthafucka Pop&quot;, :description=>&quot;Iggy Muthafucka Pop&quot;, :date=>&quot;2022-03-03 16:26&quot;, :product_id=>&quot;gid://shopify/Product/7457969438871&quot;} {:id=>37, :url=>&quot;/events/37&quot;, :name=>&quot;War on Drugs&quot;, :description=>&quot;War on Drugs&quot;, :date=>&quot;2022-03-03 13:55&quot;, :product_id=>&quot;gid://shopify/Product/7457593229463&quot;} {:id=>40, :url=>&quot;/events/40&quot;, :name=>&quot;orbi cat&quot;, :description=>&quot;orbi cat&quot;, :date=>&quot;2022-03-29 15:43&quot;, :product_id=>&quot;gid://shopify/Product/7493844467863&quot;}" total_items_count="3" class="Polaris-ResourceList">
        <li data-controller="polaris-resource-item" class="Polaris-ResourceItem__ListItem">
           <div class="Polaris-ResourceItem__ItemWrapper">

**Comment by dan-gamble** [comment]
Are you using the library from the GitHub main branch? I don't think there is a release of this library that has this in it yet.

**Comment by resistorsoftware** [comment]
OK. I am just using 0.10.1 from main yes. I guess when I look at Resource List in Polaris, and see what it offers, versus the View Components, you are correct. There is no support in View Components save for the most basic render of items, which is totally fine for me, but I was surprised to see that the one support option, with the header and total count, was in the demo, but not actually in the code. Is that common? To provide demos of things not yet in the code? It made me confused anyway. But I confuse easily. 

So anyway, thanks for confirming this for me. I will carry on and hopefully someone will update this Resource List at some point to match that of the Shopify version.

**Comment by dan-gamble** [comment]
It's because the site is in sync with the `main` branch whereas the releases aren't necessarily. Will get a new release out that has that `total_items_count` in it as I'm also in need of it! I'll update you when it's been released.

I want to try and get more of the ResourceList in sync with the actual Polaris version. The main blocker at the moment is the ResourceList in the React version is super JS heavy whereas the intention here is to lean on Hotwire / Sprinkles of Stimulus.

I'll see if there are more quick wins we can get here before trying to tackle the fuller implementation.

**Comment by resistorsoftware** [comment]
I am doing a bundle install from 0.10.1 which for all intents is **main** so I am curious as to why if the demo is pinned to main, and exhibits the header and the total count, why am I not seeing that? I guess I am hung up on that.

**Comment by dan-gamble** [comment]
I'm just going based on this and the diff: https://github.com/baoagency/polaris_view_components/releases/tag/v0.10.1

**Comment by kirillplatonov** [comment]
The demo site was auto-deployed to Heroku from `main` branch. This led to unreleased features being available in demo. I turned off auto-deploy and made a few changes to the release script in #250. Now we'll deploy only after releasing new version.

The feature you mentioned will be released next week in v0.11.0 😉

**Comment by dan-gamble** [comment]
@resistorsoftware `v0.11.0` is out now 👍
