### ISSUE TITLE
Disable previous pagination if element is empty

### ISSUE THREAD

**Issue by Kurbm** [baoagency/polaris_view_components#257]
Hey,

I just added the pagination element in the page component. 

One thing, which could be added in the documentation is, that you need to use the command "prev_url", so that the previous URL button is not disabled, since the command "previous_url" from the pagination element itself, does not work.

One question here, is there a way to disable the previous button automatically if there is no previous page?

**Comment by kirillplatonov** [comment]
Hey @Kurbm,

This is how I use it with `pagy` gem:
```erb
<%= polaris_stack(distribution: :center) do |stack| %>
  <% stack.item do %>
    <%= polaris_pagination(
      previous_url: pagy.prev && pagy_url_for(pagy, pagy.prev),
      next_url: pagy.next && pagy_url_for(pagy, pagy.next),
    ) %>
  <% end %>
<% end %>
```

When `pagy.prev` is empty previous button is disabled automatically.

**Comment by Kurbm** [comment]
@kirillplatonov thanks for letting me know. I just use now the cursor based pagination from the Shopify app itself.

Controller is then like this
    @blogs = ShopifyAPI::Blog.find(:all, params: { limit: 50, page_info: params[:page_info] })

    @next_page_info = @blogs.next_page_info
    @prev_page_info = @blogs.previous_page_info
    
    And in the view an unless statemend.
