### ISSUE TITLE
Show Previews - Side by side my own components

### ISSUE THREAD

**Issue by danielnc** [baoagency/polaris_view_components#262]
Is there a way to show polaris component previews side-by-side with my own components using lookbook?

I want to use that as the source of truth to document all components that exists on the app, but I cant find a way to "import" existing polaris components without copying them to the root of my app

I want to leverage the existing preview components and just add them to my own app

**Comment by kirillplatonov** [comment]
Hey,

It's possible to add additional preview paths for view components:
```rb
config.view_component.preview_paths << "#{Rails.root}/../polaris_view_components/demo/test/components/previews"
```

However, it requires having `polaris_view_components` repo locally as we don't ship `demo` folder and previews with the gem. One of the options would be to use git submodules to have an access to that folder locally and keep the content up to date.

**Comment by danielnc** [comment]
@kirillplatonov that would defeat the porpoue of keeping the components as our source of truth, and link it to the specific gem version so it serves as documentation
