### ISSUE TITLE
Custom primary page action

### ISSUE THREAD

**Issue by artyrcheek** [baoagency/polaris_view_components#270]
### Is there any way to create a custom page action?
Forgive me if I'm being incompetent. It seems to me there is no way of creating a custom page action.

Providing a `polaris_button_to` to the `primary_action` produces this weird empty button

![image](https://user-images.githubusercontent.com/29695801/204148615-336dc54f-141f-4cb6-9474-c55a486e1847.png)

![image](https://user-images.githubusercontent.com/29695801/204148471-7cc8a7d4-9aa6-4c6d-9045-1b234bcd4ac3.png)

**Comment by kirillplatonov** [comment]
You can customize primary action attributes like this:
```erb
<%= polaris_page_actions do |actions| %>
  <% actions.primary_action(url: "/collections", type: "submit") { "Save" } %>
<% end %>
```

**Comment by artyrcheek** [comment]
That seems to work visually, but doesn't seem to work as a submit button.

Here is some more context
```
<%= form_with(model: collection, builder: Polaris::FormBuilder) do |form| %>

  <%= polaris_layout do |layout| %>
    <%= layout.section do %>
      <%= form.errors_summary %>
    <% end %>
    <%= layout.section do %>
    <%= polaris_card do %>
      <%= form.polaris_text_field :title %>
    <% end %>
  <% end %>

  <% end %>


  <%= polaris_page_actions do |actions| %>
    <% actions.primary_action(url: "/collections", type: "submit") { "Save" } %>
  <% end %>
<% end %>
```

**Comment by kirillplatonov** [comment]
Or, if you want it to work as submit button then remove the URL param from button and put it in for attribute.

**Comment by artyrcheek** [comment]
As in `<% actions.primary_action(type: "submit", for: "/collections") { "Save" } %>`?

**Comment by kirillplatonov** [comment]
```erb
<%= form_with(model: collection, url: "/collections", builder: Polaris::FormBuilder) do |form| %>
  <%= polaris_page_actions do |actions| %>
    <% actions.primary_action(type: "submit") { "Save" } %>
  <% end %>
<% end %>
```

**Comment by artyrcheek** [comment]
That doesn't seem to work either.

Is it because
`<% actions.primary_action(type: "submit") { "Save" } %>`
is translating to
`<button `**`type="button`**`" data-controller="polaris-button" class="Polaris-Button Polaris-Button--primary">`
rather than
`<button `**`type="submit`**`" data-controller="polaris-button" class="Polaris-Button Polaris-Button--primary">`

**Comment by kirillplatonov** [comment]
Oh, sorry. The syntax was wrong. You don't need to pass `type` attribute. Use `submit` attribute instead:
```rb
<% actions.primary_action(submit: true) { "Save" } %>
```

You can always find up to date list of attributes in components source code: https://github.com/baoagency/polaris_view_components/blob/main/app/components/polaris/headless_button.rb#L27

**Comment by artyrcheek** [comment]
Thanks!
