### ISSUE TITLE
Question about Polaris

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#271]
Did the authors of Polaris, Shopify, really setup up their styles with RGD colors like I see in this repo? 

     background-color: rgb(246, 246, 247)

Is that unique to this repo? Just curious. Would it not have been better to have swappable palettes? I enjoy how Tailwind does color and palettes. So I am wondering, did Shopify miss the bus or something?

**Comment by kirillplatonov** [comment]
Most of the time Polaris uses Tokens via CSS variables: https://polaris.shopify.com/tokens/colors
This gem is still on Polaris 7, so some components might be using an old approach. I'm working on upgrading gem to Polaris 10.
