### ISSUE TITLE
Checkbox question

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#275]
I can render a checkbox with no **checked** and that is fine.
I can render a checkbox with **:indeterminate** and that is fine. 

But I cannot render a checkbox as checked?

**Comment by resistorsoftware** [comment]
Also, how to render the checkbox with labels that are actually links? What would jesus do? The checkbox and label render as a block div but I want the checkbox to have links beside it for text, not just a label. Any good patterns for this? Wrapping both in a box is the only choice I guess?

**Comment by kirillplatonov** [comment]
> Also, how to render the checkbox with labels that are actually links? What would jesus do? The checkbox and label render as a block div but I want the checkbox to have links beside it for text, not just a label. Any good patterns for this? Wrapping both in a box is the only choice I guess?

For simple link use:
```rb
<%= polaris_checkbox(label: "Basic <a href='#'>checkbox</a>".html_safe) %>
```

For something more complex:
```rb
<% custom_label = capture do %>
  <div>
    <span>Custom label</span>
    <a href="#">with a link</a>
  </div>
<% end %>
<%= polaris_checkbox(label: custom_label) %>
```

**Comment by Kurbm** [comment]
Hey @kirillplatonov,

the checked: true only works for the normal checkbox tag.

But does not work, if you use the form.polaris_check_box tag. Is there a way to precheck the form tag as well?

Disabled: true e.g. works.

**Comment by kirillplatonov** [comment]
With form builder you'll need to set this attribute via model instead. Eg:
```rb
product = Product.new(accept: true)
```
```erb
<%= form_with(model: product, builder: Polaris::FormBuilder) do |form| %>
  <%= form.polaris_check_box(:accept,
    label: "Basic checkbox",
    help_text: "Customers must review their order details before purchasing.",
  ) %>
<% end %>
```

**Comment by kirillplatonov** [comment]
@Kurbm fixed checkbox behavior with form builder:
https://github.com/baoagency/polaris_view_components/pull/281
