### ISSUE TITLE
Support for ViewComponent v3

### ISSUE THREAD

**Issue by Spone** [baoagency/polaris_view_components#277]
Hello! I'd like to know if you're planning on supporting ViewComponent v3. There are currently two release candidates ([v3.0.0.rc1](https://github.com/ViewComponent/view_component/releases/tag/v3.0.0.rc1) and [v3.0.0.rc2](https://github.com/ViewComponent/view_component/releases/tag/v3.0.0.rc2)) that you can try out.

I think the deprecation slots setter methods will generate the most work (you have to use `with_SLOT_NAME` instead).
I'm currently exploring the idea of providing a linter/codemod to help with this: https://github.com/ViewComponent/view_component/pull/1669

Would you be interested in trying it out and providing feedback?

**Comment by kirillplatonov** [comment]
Hey @Spone,

Yeah, we plan to upgrade. The codemod for slots looks very useful. I will try it out when I'll be working on upgrade 👍

**Comment by kirillplatonov** [comment]
@Spone I just used it during the upgrade to ViewCompoent v3 and it was extremely useful. We had only 3 false positive warnings on our codebase:
```
File: /Users/kirill/Code/polaris_view_components/app/components/polaris/base_radio_button.rb
=> line 32: maybe replace `.radio_button` with `.with_radio_button`

File: /Users/kirill/Code/polaris_view_components/app/components/polaris/page_component.html.erb
=> line 70: maybe replace `.action` with `.with_action`

File: /Users/kirill/Code/polaris_view_components/app/components/polaris/resource_item/shortcut_actions_component.html.erb
=> line 16: maybe replace `.action` with `.with_action`
```
All of them are custom methods that start from the same name as a slot. It would be very helpful to see this as a part of ViewComponent. Thanks for your work on this ❤️

**Comment by kirillplatonov** [comment]
@Spone until https://github.com/ViewComponent/view_component/pull/1669/files is not merged would you mind if I include this codemod to our gem as a rake task? This will help to upgrade apps that are relying on our library

**Comment by Spone** [comment]
@kirillplatonov I have a counteroffer 😀 work with me to get the PR past the finish line and get it merged in VC!

**Comment by kirillplatonov** [comment]
@Spone I'm in 🙌

**Comment by Spone** [comment]
I'll get in touch with you next week!
