### ISSUE TITLE
Cards and Actions question

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#285]
A clicked Polaris link, works just off the target. Provide some data, and you can easily redirect, for example, back to Shopify. But if use links generated in actions, that no longer works, and the target is actually buried in the parent! What would be a nicer way to accomplish the same thing, without the hacky referencing of the parents? 

Example code from the Erb template and stimulus controller actions:

    <%= polaris_card(title: "Thing Management", actions: [
      { content: "View List", url: things_path },
      { content: "Return to Shopify Collection", url: "#", "data-id": @collection.legacyResourceId, "data-action": "click->things#shopifyCollection" }
    ]) do %>

And the Stimulus. Note the target and moving up the parents to get at the the needed data.

    export default class extends Controller {
      connect() {
        console.log("In the Things Controller domain");
      }

      shopifyCollection(e) {
        e.preventDefault();
        console.log("target ", e.target);
        const redirect = Redirect.create(window.app);
        redirect.dispatch(Redirect.Action.ADMIN_PATH, `/collections/${e.target.parentNode.parentNode.dataset.id}`);
      }
    }

**Comment by kirillplatonov** [comment]
You need to pass data attributes to actions using hash. This way data can be properly parsed and passed to an underlying Button component.

```erb
<%= polaris_card(title: "Thing Management", actions: [
  { content: "View List", url: things_path },
  { content: "Return to Shopify Collection", url: "#", data: { id: @collection.legacyResourceId, action: "click->things#shopifyCollection" } }
]) do %>
```

**Comment by resistorsoftware** [comment]
I don't see how that answers the question, where the Stimulus has to bump parent to parent from the target but OK. sure. I will just use that. It is not the end of the world. Thanks.
