### ISSUE TITLE
add darker background to disabled fields

### ISSUE THREAD

**Issue by yshmarov** [baoagency/polaris_view_components#289]
both of these fields are disabled, but there is no visual indicator that the empty input field is disabled -> drives confusion.

<img width="203" alt="Screenshot 2023-04-20 at 11 22 39" src="https://user-images.githubusercontent.com/13472945/233321505-80f8a733-de9b-47ff-b9d8-9c4c8aa8e7ab.png">

maybe we could add _cursor-_disabled and _darker background_ to disabled fields for a better visual indicator?

**Comment by kirillplatonov** [comment]
Disabled fields already have styles provided by Polaris:
<img width="597" alt="CleanShot 2023-04-20 at 15 25 40@2x" src="https://user-images.githubusercontent.com/839922/233352251-c971958c-d70a-41ef-a864-8e845e825290.png">

Code:
```erb
<%= polaris_text_field(
  value: 'Jaded Pixel',
  label: 'Non disabled',
) %>
<%= polaris_text_field(
  value: 'Jaded Pixel',
  label: 'Disabled',
  disabled: true,
) %>

<%= polaris_spacer(vertical: :base) %>

<%= polaris_text_field(
  label: 'Non disabled',
) %>
<%= polaris_text_field(
  label: 'Disabled',
  disabled: true,
) %>
```

Maybe you're setting it via input arguments right now?
