### ISSUE TITLE
Dropzone issue with Chrome

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#299]
If I use The Hotwire App and Rails 7, and Dropzone with Firefox and Safari, the upload works perfect. If I use Chrome I get a 422 error and it complains about CSRF token. 

Why is Chrome alone broken in this way? What can I do to fix that? Adding a header to the post on the upload does not seem to fix this. 

    path="/rails/active_storage/direct_uploads?shop=
    
    generates ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):

**Comment by kirillplatonov** [comment]
This is not a Dropzone issue. ActiveStorage uses CSRF protection which uses cookies. Since cookies are not available in iframe anymore in certain browsers the direct upload will fail. The only way I know to resolve this is to turn off CSRF for ActiveStorage:
```rb
class DirectUploadsController < ActiveStorage::DirectUploadsController
  skip_forgery_protection
end
```

**Comment by resistorsoftware** [comment]
Yes. I had a moment there where I felt all lost, but indeed, that was all there was to it. Thanks!
