### ISSUE TITLE
Navigation Component highlighting noth nav links on similar URLs

### ISSUE THREAD

**Issue by 3lackRos3** [baoagency/polaris_view_components#304]
I'm experiencing a problem with the navigation component to highlight the current link. The issue is that if I have two navigation items with URLs like example.com/consumer/friend and example.com/consumer/unfriend, when the user is on a page like example.com/consumer/xyz, both navigation links are highlighted.

I think the return for this method https://github.com/baoagency/polaris_view_components/blob/d04ea129939d803e64acc19f215bad2968632f03/app/components/polaris/shopify_navigation_component.rb#L56

should be  `url.split("?").first == request.path`

**Comment by kirillplatonov** [comment]
Request path uses partial matching and it was done intentionally to highlight nested pages under same namespace in navigation. If you don't like default auto-detection of current link you can always turn it off and set active link manually using any rule you prefer.
