### ISSUE TITLE
Custom CSS Class for Polaris Components

### ISSUE THREAD

**Issue by kgorshkov** [baoagency/polaris_view_components#306]
Hi, Is there a way to add a custom css class for any component?

For example:

`<%= polaris_icon(name: "CirclePlusMinor", class: "customIconCss") %>`

Would result in:

```
<span class="Polaris-Icon customIconCss">
    <svg class="Polaris-Icon__Svg" ... >...</svg>
</span>
```

This would be a very useful feature to be able to fine-tune the layout of components and customize them.

Thanks,

KG

**Comment by kirillplatonov** [comment]
Hi,

You can use `classes` attribute for that. It's support by almost all components: https://github.com/baoagency/polaris_view_components/blob/main/app/components/polaris/icon_component.rb#L27
```erb
<%= polaris_icon(name: "CirclePlusMinor", classes: "customIconCss") %>
```
