### ISSUE TITLE
IconComponent ViewHelper File I/O Memory

### ISSUE THREAD

**Issue by kgorshkov** [baoagency/polaris_view_components#308]
For apps that utilize the same icons frequently and repeatedly, there is a memory bloat issue.  File.read i/o or the Nokogiri parsing in polaris_icon_source() are the likely reasons.  An icon file can be loaded from the filesystem once and the parsed data cached/stored for subsequent references of the same icon.  Alternately there might some way to use the Rails Asset Pipeline here for icon references.

https://github.com/baoagency/polaris_view_components/blob/14223cc178148fa9dcdb61825991c03e61525f2e/app/helpers/polaris/view_helper.rb

Thank you

**Comment by kirillplatonov** [comment]
Yeah, memoizing icon by name should help in that case. Feel free to open the PR for that 🙂

**Comment by kgorshkov** [comment]
It looks like hooking into the Rails Asset Pipeline for the icon files by extending Rails::Engine is the cleanest approach:

https://guides.rubyonrails.org/asset_pipeline.html#adding-assets-to-your-gems

..but this approach would load all icon files into the asset pipeline, so maybe the polaris_view_components gem user would be instructed to explicitly define icon file assets for precompilation:

https://guides.rubyonrails.org/engines.html#separate-assets-and-precompiling

...and then add ViewHelper exception handler logic to fallback to File.read if the icon requested is not present in the pipeline:

https://guides.rubyonrails.org/asset_pipeline.html#raise-an-error-when-an-asset-is-not-found

**Comment by kirillplatonov** [comment]
The typical app will use a limited number of icons (10-20). Loading all 500 polaris icons into assets pipeline in that case is not a good idea. It will slow down assets precompilation. And having users to manually specify icons that they use is also not a great experience. I think keeping adding memoization to existing File.read implementation will be the optimal solution.
