### ISSUE TITLE
Choice List in a Horizontal layout?

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#316]
I have a choice list of 6 things. Take zero, one or more of the choice list.

I want to render them all on a line, so it seems natural to use the horizontal stack block

`<%= polaris_horizontal_stack(gap: "4", block_align: :center, wrap: false) do %>`

But rendering a choice list in this just uses a single vertical column. Anyway to render a choice list horizontally?

**Comment by kirillplatonov** [comment]
OptionList doesn't support horizontal layout. You can use Popover with custom content inside and put required layout there. Or just use horizontal stack with checkboxes.
