### ISSUE TITLE
Checking for ComboBox

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#317]
Just checking.. but there is no combo box right? 

Looking to pull off a simple list of options anchored to a button 

<img width="207" alt="image" src="https://github.com/baoagency/polaris_view_components/assets/123307/81dbe7f3-b1f6-4b7d-890b-b2ebfea4be1b">

**Comment by kirillplatonov** [comment]
There's option list: https://polarisviewcomponents.org/lookbook/inspect/option_list/multi_choice
