### ISSUE TITLE
PAGINATION Question

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#321]
Say I render a Resource List and want to page through the results from pages 1 through oh, I dunno, 432.

I render the Pagination component and it comes with two links... but actually, I am using JS and Hotwire, turbo, Stimulus of Rails 7 era code... can these Previous and Next controls be JS? What would that look like?

**Comment by kirillplatonov** [comment]
Since you're using Turbo you should be fine with server pagination like [pagy](https://github.com/ddnexus/pagy). No need for JS. Here's a nice guide on Gorails: https://gorails.com/episodes/how-to-add-pagination-for-blog-posts-in-rails

**Comment by resistorsoftware** [comment]
Actually, while pagy is fine for simple things, when you have a more complex app, it is not helpful. All it provides are GET requests with a page param. I have a complex form setup with 12 parameters. I need to get those to the search, which then can function and work off paging. 

So I guess the gist is, I cannot use this component excepting in a simpler scenario where paging is done without much filtering. It is too bad, would be nice to have a JS action assignable to Prev / Next. 

Something for the future I guess. For now, I will have to just write my own Prev / Next links I guess. Will look like crap but at least it will get the job done!
