### ISSUE TITLE
horizontal_stack: ViewComponent::MissingPreviewTemplateError

### ISSUE THREAD

**Issue by yshmarov** [baoagency/polaris_view_components#322]
I am sure your error monitoring tool picked it up, but just in case:

https://polarisviewcomponents.org/lookbook/inspect/horizontal_stack/align

<img width="1128" alt="Screenshot 2023-09-26 at 17 12 04" src="https://github.com/baoagency/polaris_view_components/assets/13472945/b0b35085-de7e-40ab-b2b0-026870327f23">

**Comment by kirillplatonov** [comment]
Thanks! Removed this preview in the latest release. We don't have error monitoring for polarisviewcomponents.org. Might be good idea to add Sentry 😅
