### ISSUE TITLE
Is it possible to make an index table with views and search?

### ISSUE THREAD

**Issue by rbarreca** [baoagency/polaris_view_components#340]
I'm looking to add view tabs and search to an index table a la https://polaris.shopify.com/components/tables/index-table?example=index-table-with-views-search-filter-sorting. Is this possible now? If not, could someone guide me on how I might solve it and contribute a PR for it?

**Comment by yshmarov** [comment]
@rbarreca do you want to search with javascript, or rails?

You can combine these 2 components
- https://polarisviewcomponents.org/lookbook/inspect/filters/with_resource_list
- https://polarisviewcomponents.org/lookbook/inspect/data_table/sortable
to achieve something like this:
<img width="854" alt="Screenshot 2023-11-22 at 21 40 48" src="https://github.com/baoagency/polaris_view_components/assets/13472945/2d718fd2-6d2e-4a74-aaa8-8dad5abd2565">

**Comment by rbarreca** [comment]
@yshmarov oh cool. Thank you.

Do you have any good resources/tips to point me to on how this would work with a paginated table (1,000+ items)?

**Comment by rbarreca** [comment]
I've got the Turbo part of the search working, but is there a way to set the when trying to add the Stimulus's data-action param (e.g. `data: {action: "input->search-form#search"}`) to the filter's text field? Digging around I see two potential problems:

1. I'm not sure the gem even provides a way for the caller to set data-action
2. The gem already sets data-action on the text field, so even if I could set it through API I'd be overwriting that

What is the recommended approach to hook Stimulus into Polaris components @kirillplatonov?

**Comment by forsbergplustwo** [comment]
@rbarreca - You can pass additional parameters through to the underlying input (text, selects, checkboxes etc.) using `input_options` key, like this:

```erb
<% filters.with_query(
        name: "q[search_text_cont]",
        value: params.dig(:q, :search_text_cont),
        placeholder: t(".search_placeholder"),
        input_options: {
          data: { action: "input->filters#submit change->filters#submit" },
        },
      ) %>
```

**Comment by kirillplatonov** [comment]
Yep, `input_options` is the way to go. `TextFieldComponent` sets its own data attributes, but it appends them to options you provided: https://github.com/baoagency/polaris_view_components/blob/main/app/components/polaris/text_field_component.rb#L147

**Comment by rbarreca** [comment]
Ah, thank you both. I should've known this. I forgot I asked basically the same question weeks ago on a different component.
