### ISSUE TITLE
Button styles

### ISSUE THREAD

**Issue by forsbergplustwo** [baoagency/polaris_view_components#368]
Button styles need aligning with the new v12 styles. Default and Primary are ok, but we need to check all the other variants.

**Comment by kirillplatonov** [comment]
@forsbergplustwo some CSS overrides seems to cause the issue. Without them buttons looks the same:
![CleanShot 2024-02-09 at 20 27 19@2x](https://github.com/baoagency/polaris_view_components/assets/839922/0b3ec798-a4e1-4ac8-aaf2-59b02f840f1d)
![CleanShot 2024-02-09 at 20 28 20@2x](https://github.com/baoagency/polaris_view_components/assets/839922/0a575c93-a8ca-4bfc-ae43-911dbbf9c0c7)
![CleanShot 2024-02-09 at 20 28 25@2x](https://github.com/baoagency/polaris_view_components/assets/839922/cca7de62-0aec-468c-aac9-3d84fc0faa6e)

**Comment by forsbergplustwo** [comment]
Yeah, I'll scope that to Banner, Modal, Card etc. that want the button text larger and bold. But this task is more about the other button styles, like Critical/Destroy etc.

**Comment by forsbergplustwo** [comment]
EDIT: Just realized I'm seeing the "Mobile" styling of the buttons, because I've got 2 windows side by side on my laptop. So I'll move those parts to a @media query instead 😅

We still need to check on the other button styles though.

**Comment by kirillplatonov** [comment]
Got it 🙂

**Comment by forsbergplustwo** [comment]
@kirillplatonov - This one is now done.. see #383 for screenshots 🎉 

Note: The new Polaris v12 does not have "outline" buttons, so I've silently dropped the class from being added in the component for now, making them a "normal" button:

https://github.com/baoagency/polaris_view_components/blob/b23ec0635b5d1f8413ef397fe2d73d089b519ed2/app/components/polaris/headless_button.rb#L86

Not sure if there's a better fallback for these as I don't remember using them anywhere, but let me know if you think it should be done different.
