### ISSUE TITLE
Cleanup stylesheets directory structure

### ISSUE THREAD

**Issue by forsbergplustwo** [baoagency/polaris_view_components#385]
As we are releasing the Polaris v12 changes as a breaking 2.0 version, we can go ahead and re-organize the stylesheet directories and files to keep it consistent.

**Comment by kirillplatonov** [comment]
Not sure if it makes sense to spend time on this since we'll remove these customization with new Polaris release anyway. @forsbergplustwo maybe let's keep it as is, what do you think?

**Comment by forsbergplustwo** [comment]
@kirillplatonov  I can do today 😊 My plan was just moving files from `stylesheets/polaris_v12_overrides` into the normal `stylesheets/polaris_view_components` folder and updating imports in `polaris_view_components.pcss`.

**Comment by kirillplatonov** [comment]
Okay 👍 Otherwise I think #330 is ready to be merged to `main`. I upgraded both of my apps and everything looks great. Once we merge it I will upgrade icons too and we can publish v2.0 this week.

**Comment by forsbergplustwo** [comment]
Awesome, also have it running nicely on a couple of mine.. so cool with having this as the released version 🎉 I've pushed up https://github.com/baoagency/polaris_view_components/issues/385 now with the file re-organization.

**Comment by kirillplatonov** [comment]
Closed by https://github.com/baoagency/polaris_view_components/pull/398
