### ISSUE TITLE
contextual save bar does not detect Shopify embedded state

### ISSUE THREAD

**Issue by uurcank** [baoagency/polaris_view_components#404]
[Contextual save bar](https://polarisviewcomponents.org/lookbook/inspect/contextual_save_bar/default) should ideally detect if the Shopify app bridge is present and use [ui-save-bar component](https://shopify.dev/docs/api/app-bridge-library/web-components/ui-save-bar) when embedded in Shopify

Without this change, the save bar renders within the embedded app frame. The save bar is designed to appear in the top frame so it does not currently work as expected.
 
 The [stimulus controller](https://github.com/baoagency/polaris_view_components/blob/b56fed759dcaaaefb7b7bb8839921a950473617f/app/assets/javascripts/polaris_view_components/frame_controller.js#L12) can be expanded to check for embedded state and render ui-save-bar instead.

**Comment by kirillplatonov** [comment]
Contextual save bar component designed for standalone non-embedded apps that are using Frame. For embedded apps we need to use ui-save-bar from AppBridge. I don't plan to add integration with AppBridge to Polaris ViewComponents as it will make library even harder to maintain with constant Polaris + AppBridge changes. Instead I will keep adding Stimulus controllers for AppBridge integration to Shopify Hotwire Template repo, including ui-save-bar.
