### ISSUE TITLE
Option to hide label for polaris_collection_check_boxes

### ISSUE THREAD

**Issue by Kurbm** [baoagency/polaris_view_components#411]
Hey,

is it possible to hide or change the auto generated label of the polaris_collection_check_boxes component?

Thanks and best,
Kevin

**Comment by k0va1** [comment]
Hey! Yep, it's quite easy. You just need to pass `title_hidden: true` as an argument to `polaris_collection_check_boxes`, but there is an issue ATM

You can try again after this https://github.com/baoagency/polaris_view_components/pull/412 will be merged. Thanks 🙏

**Comment by kirillplatonov** [comment]
#412 merged 👍
