### ISSUE TITLE
Rails time_select with Polaris

### ISSUE THREAD

**Issue by elioncho** [baoagency/polaris_view_components#418]
Hi, I was wondering if there's a way to render something similar to Rails's time_select using Polaris?

**Comment by forsbergplustwo** [comment]
Nothing native currently in the repo. You could use a js based solution on top of the `polaris_text_field` component, similar to this:

```
        <%= polaris_text_field(
          name: "q[shop_order_created_at_between]",
          value: filter_created_value(params[:q]),
          label_hidden: true,
          placeholder: t(".created"),
          input_options: { data: {daterangepicker_target: 'input'}},
        ) %>
```

And then hooking it up via Stimulus or similar.
