### ISSUE TITLE
How to put header icon?

### ISSUE THREAD

**Issue by uurcank** [baoagency/polaris_view_components#421]
Shopify has a notification icon at the top left of the frame, next to account dropdown

How can  a similar icon be added in [PVC frame](https://polarisviewcomponents.org/lookbook/inspect/frame/default)?

<img width="332" alt="Screenshot 2024-06-16 at 8 14 30 AM" src="https://github.com/baoagency/polaris_view_components/assets/6050683/27aa8e6e-1728-46e3-953a-fa53c7273c7a">

**Comment by kirillplatonov** [comment]
We don't have anything for that out of the box. Feel free to contribute.

**Comment by kirillplatonov** [comment]
Should be possible with new `secondary_menu` slot of Frame component, added by @remy727: https://github.com/baoagency/polaris_view_components/pull/428#event-13434894406

Note: not released yet, available in `main` branch
