### ISSUE TITLE
Support for Polaris v13 styles

### ISSUE THREAD

**Issue by remy727** [baoagency/polaris_view_components#422]
I saw some deprecated components are still being used in Polaris ViewComponents:
- `Caption`
- `DisplayText`
- `Heading`
- `Subheading`
- `Text Container`
- `Text Style`
- `Stack`
- `HorizontalStack `- renamed to `InlineStack`
- `VerticalStack `- renamed to `BlockStack`
- `Card ` - this still uses props of `LegacyCard` which is deprecated.

We are re-building the Shopify app UI with the latest version(`2.0.1`).
But we must upgrade to a new version that supports Polaris v13.
Therefore, getting new versions as soon as possible would greatly help us.

Is this on your roadmap? When can I expect to try the new version?
Thank you!

**Comment by kirillplatonov** [comment]
Polaris ViewComponents v2.x is based on Polaris v11 with new UI turned on. There's no plans to upgrade to v13 as Polaris changes very quickly without adding any value to what we already have. And visually it's the same. We'll wait for next major Polaris release.
