### ISSUE TITLE
Taping outside of navigation doesn't close it on Frame component

### ISSUE THREAD

**Issue by remy727** [baoagency/polaris_view_components#424]
On Frame component, navigation menu is not being closed when clicking outside of navigation.
You can try [here](https://polarisviewcomponents.org/lookbook/preview/frame/default) on mobile.

![image](https://github.com/baoagency/polaris_view_components/assets/69775411/6036f4ec-5542-44f5-baff-186d5778bbb9)

I confirmed Shopify Frame component supports this.

**Comment by kirillplatonov** [comment]
Check out source code of FrameComponents class and views. You might need to add custom JS/CSS to Polaris ViewComponents for this feature.

**Comment by remy727** [comment]
@kirillplatonov, I created #426. It was simpler than I thought.
