### ISSUE TITLE
Adding target: :top to polaris_button_to adds it to the button not the form

### ISSUE THREAD

**Issue by rbarreca** [baoagency/polaris_view_components#448]
I want a button to open in the _top frame (I'm navigating the user to Quickbooks to authenticate). Is there a way to do that with `polaris_button_to`?

This doesn't work as it adds the target to the button not the form element:
```
<%= polaris_button_to("Authenticate with Quickbooks", 
  @quickbooks_authenticate_url,
  { 
    method: :get,
    target: "_top" 
  }
)
%>
````

This works but is gross:
```
<%= polaris_button_to("Authenticate with Quickbooks", 
  @quickbooks_authenticate_url,
  { onclick: "window.top.location = '#{quickbooks_authenticate_url}'" }
)
%>
```

**Comment by kirillplatonov** [comment]
`polaris_button_to` will generate form with submit button under the hood. It's easier to use plain `polaris_button` in your case:
```erb
<%= polaris_button(url: "https://shopify.dev", target: "_top") { "Authenticate with Quickbooks" } %>
```
