### ISSUE TITLE
How to add remote data in DataTable?

### ISSUE THREAD

**Issue by wntechs** [baoagency/polaris_view_components#450]
The current DataTable and IndexTable provide only server side data feature. I am trying to add remote data using ajax using jquery's datatable plugin. It worked but the DataTable layout looks a bit broken or inconsistent. What would be the right approach for this?

**Comment by wntechs** [comment]
Thanks for the example links @kirillplatonov . I will have a look and see.

**Comment by cesarho** [comment]
Hi @kirillplatonov,

In this way, the action controller is linked to the div. Is it possible pass the controller to the <input> tag?

```
          <%= polaris_filters do |filters| %>
            <% filters.with_query(
              name: :query,
              placeholder: "Filter items",
              data: { action: "autosubmit#submit" }
            ) %>
          <% end %>
```

![Image](https://github.com/user-attachments/assets/2873be94-aded-4355-a45c-a7deee31bc38)
