### ISSUE TITLE
before_render/wrap_children not wrapping child

### ISSUE THREAD

**Issue by drnic** [baoagency/polaris_view_components#48]
I've got a simple view with a layout section + card with `sectioned: true`. This should wrap the inner element in a div. But it's not and I can't quite figure out where/why it's not.

```
<%= polaris_layout do |layout| %>
  <% layout.section do %>
    <%= polaris_card(title: "Install Live Links designer", sectioned: true) do %>
      <p>View a summary of your online store’s performance.</p>
    <% end %>
  <% end %>
<% end %>
```

In the resulting output, the `<p>` inner HTML is not wrapped in a `div.Polaris-Card__Section` but it should be.

AFAICT, the `Polaris::Card::Component#before_render` is working and setting `@_content` correctly.

```
      def before_render
        super

        return unless @sectioned

        wrap_children! "Polaris-Card__Section"
        pp @_content
      end
```

Logs the correct wrapped DOM:

```
"<div class=\"Polaris-Card__Section \"><p>View a summary of your online store’s performance.</p></div>\n"
```

Any ideas why `@_content` is correct but then it reverts to the inner HTML only later?

This feature works in your demo app, and for both the demo app + my own app I'm using #47 PR and view_component 2.36.0

**Comment by kirillplatonov** [comment]
Please pull the latest code from master. The card component has been rebuilt yesterday and it's not using `wrap_children` anymore. We're in the process of migrating all other components.

**Comment by kirillplatonov** [comment]
The latest component with `wrap_children` has been rebuilt.

**Comment by drnic** [comment]
Thanks, I've caught up on all the new stuff and new syntax. Looking good.
