### ISSUE TITLE
Wrapping doesn't work in ViewComponent 2.35

### ISSUE THREAD

**Issue by kirillplatonov** [baoagency/polaris_view_components#5]
I installed `view_component` v2.35.0 initially. But it doesn't seem to work properly. This code breaks:
```ruby
def before_render
  super

  return unless @sectioned

  wrap_children! 'Polaris-Card__Section'
end
```

As a result wrapping in cards and over components doesn't work:
<img width="661" alt="CleanShot 2021-07-26 at 12 54 27@2x" src="https://user-images.githubusercontent.com/839922/126990039-a4a60e42-20b7-44a9-9bca-b6700c091057.png">

**Comment by kirillplatonov** [comment]
I set `view_component` dependency to `< 2.35.0` for now in #4.

**Comment by dan-gamble** [comment]
I think this was to do because we changed the component instance variable. `2.3.5` changed that. That's the first place we need to look
